## Netlify configuration for mobile redirect edge function
## Publish folder assumes Vite build output lives in dist/
[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
  function = "device-redirect"
  path = "/*"

## SPA fallback (desktop)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
# Netlify config for Mobile (Expo Web) build
[build]
  command = "npm run build:netlify"
  publish = "dist"
  # Set API/base env vars (VITE_API_BASE, EXPO_PUBLIC_API_URL, MOBILE_WEB_TABLET_POLICY) in Netlify UI.

# Edge function for device redirect (/ -> /m on mobile). File: netlify/edge-functions/device-redirect.js
[[edge_functions]]
  function = "device-redirect"
  path = "/*"

# SPA fallback so client-side routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Optional) Security headers
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

# Long cache for hashed assets
[[headers]]
  for = "/_expo/static/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
