# Netlify config for Mobile (Expo Web) build
[build]
  command = "npx expo export -p web"
  publish = "dist"
  # If you need environment vars (e.g. API base): set in Netlify UI, NOT here.

# SPA fallback so client-side routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Optional) Security headers
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

# Long cache for hashed assets
[[headers]]
  for = "/_expo/static/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
